version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - model
      - database
  frontend_admin:
    build:
      context: ./frontend_admin
    ports:
      - "8081:80"
    depends_on:
      - model
      - database
  model:
    build:
      context: ./model
    ports:
      - "5000:5000"
  database:
    build:
      context: ./database
    ports:
      - "5050:5050"
