version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - database
  frontend_admin:
    build:
      context: ./frontend_admin
    ports:
      - "8081:80"
    depends_on:
      - backend
      - database
  backend:
    container_name: backend
    platform: linux/x86_64
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/local.env
    depends_on:
      - database
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
  database:
    container_name: database
    platform: linux/x86_64
    build: ./database
    ports:
      - "3307:3306"
    volumes:
      - ./database/data:/docker-entrypoint-initdb.d
      - ./database/cnf:/etc/database/cnf
    env_file:
      - ./database/local.env
    tty: true
