version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    image: lamducanh/uetas-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - database
  frontend_admin:
    build:
      context: ./frontend_admin
    image: lamducanh/uetas-frontend-admin
    ports:
      - "8081:80"
    depends_on:
      - backend
      - database
  backend:
    container_name: backend
    platform: linux/x86_64
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: lamducanh/uetas-backend
    restart: unless-stopped
    tty: true
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
  database:
    container_name: database
    platform: linux/x86_64
    build: ./database
    image: lamducanh/uetas-database
    ports:
      - "3307:3306"
    tty: true
